name: "Pogoda"

on:
  workflow_dispatch:
    inputs:
      miasto:
        description: "Miasto"
        required: true
        default: "Torun"

jobs:
  pogoda_dla_miast:
    name: "Pogoda dla miast"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Run Script"
        run: |
          echo "${{ secrets.API_KEY }}" >> temp.file
          cat temp.file
          bash ./start.sh "${{ github.event.inputs.miasto }}" "${{ secrets.API_KEY }}" >> $GITHUB_STEP_SUMMARY